name: CI

on:
  push:
    branches: ['deploy']
  pull_request:
    branches: ['deploy']

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Check TypeScript types
        run: npm run check-types

      - name: Check ESLint
        run: npm run lint

      - name: Check Prettier formatting
        run: npm run check-formatting

  build-image:
    needs: checks
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Build Docker image
        run: npm run build-image
